"""Generate the browser's offline scene catalog from the typed Python source."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from yanzhang_core.scenario_profiles import scenario_catalog  # noqa: E402

DESTINATION = ROOT / "gongwen_web/static/scenario_catalog.js"


def build_catalog_javascript() -> str:
    """Serialize only public catalog data; no runtime state or external I/O."""

    payload = json.dumps(scenario_catalog(), ensure_ascii=False, indent=2)
    return (
        "// Generated by scripts/build_scenario_catalog.py. Do not edit by hand.\n"
        '"use strict";\n'
        "(function (root, catalog) {\n"
        '  if (typeof module === "object" && module.exports) module.exports = catalog;\n'
        "  root.YanzhangScenarioCatalog = catalog;\n"
        f"}})(globalThis, {payload});\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Check the generated file without writing"
    )
    args = parser.parse_args()
    expected = build_catalog_javascript()
    if args.check:
        actual = DESTINATION.read_text(encoding="utf-8") if DESTINATION.exists() else ""
        if actual != expected:
            print("Scenario catalog is stale; run scripts/build_scenario_catalog.py.")
            return 1
        return 0
    DESTINATION.write_text(expected, encoding="utf-8")
    print(f"Generated {DESTINATION.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
